#!/bin/bash

create_dir_structure (){
    if [ -z "$(find $PROJECT_DIR -mindepth 1 -maxdepth 1 2>/dev/null)" ]; then
        mkdir $PROJECT_DIR
        mkdir $PROJECT_DIR/objects
        mkdir $PROJECT_DIR/branches
        mkdir $PROJECT_DIR/logs
        mkdir $PROJECT_DIR/refs
        touch $PROJECT_DIR/HEAD
        exit 0
    else
        echo "There already exists a cookie repository at this location!"
        echo "Check directory contents of $PROJECT_DIR"
        help
        exit 1
    fi
}

help (){
    echo "Usage: cookie init [-fdh]"
    echo "cookie init -f             --> Force clone when destination is not empty"
    echo "cookie init -d [directory] --> Clone to specific directory."
    echo "cookie init -h             --> Help page"
}

while getopts ":f:d:h" o; do
    case "${o}" in
        f)
            rm -rf $PROJECT_DIR
            create_dir_structure
            ;;
        d)
            destination_directory=${OPTARG}
            PROJECT_DIR=$destination_directory/.cookie
            if [ ! -d $destination_directory ]; then
                mkdir $destination_directory
            fi
            echo "Initializing repository inside $destination_directory..."
            create_dir_structure
            ;;
        h|*)
            help
            exit 0
            ;;
    esac
done

